spring.application.name=tutor-service
server.port=${PORT:8080}
spring.data.mongodb.host=cluster0.zvntui7.mongodb.net
spring.data.mongodb.port=27017
spring.data.mongodb.database=univet
spring.data.mongodb.username=luanapaivace_db_user
spring.data.mongodb.password=egfmQRNZcYpGZdWh
spring.data.mongodb.authentication-database=admin
